import { mkdir, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { command, evaluate, job, value, vaultPath } from './lab-cli.mjs';

await mkdir('test-results', { recursive: true });
const result = await job(`
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const checks=[];
function check(name,passed,detail) {checks.push({name,passed:!!passed,detail});if(!passed)throw Error(name+': '+JSON.stringify(detail));}
const ws=app.workspace;
let plugin=app.plugins.plugins['window-title'];
if(!plugin)throw Error('Window Title must be enabled in Title Lab.');
const previousTemplate=plugin.template;
const previousLeaf=ws.getMostRecentLeaf(ws.rootSplit);
const main=ws.getLeaf('tab');
const pops=[];
let graph=null;
const native=container=>container.win.electronWindow.getTitle();
const expected=container=>app.getAppTitle(ws.getMostRecentLeaf(container)?.getDisplayText().trim()??'');
const doc=()=>app.setting.popout?.win.document??app.setting.contentEl.ownerDocument;
const ui=()=>doc().querySelector('.window-title-settings');
const textarea=()=>ui().querySelector('textarea');
const input=(el,text)=>{el.value=text;el.dispatchEvent(new el.ownerDocument.defaultView.Event('input',{bubbles:true}));};
const button=(name,root=ui())=>[...root.querySelectorAll('button')].find(b=>b.textContent===name);
try {
  app.setting.close();
  await main.openFile(app.vault.getAbstractFileByPath('Welcome.md'));ws.setActiveLeaf(main,{focus:true});
  plugin.setTemplate('{{vault}} — {{title}}');await wait(200);
  check('main default title',document.title==='Title Lab — Welcome',document.title);
  for(const file of ['Projects/Planning.md','Projects/Кириллица 🪟.md']) {const leaf=ws.openPopoutLeaf();pops.push(leaf);await leaf.openFile(app.vault.getAbstractFileByPath(file));}
  await wait(300);
  const containers=[ws.rootSplit,...pops.map(l=>l.getContainer())];
  check('three independent contexts',containers.map(c=>c.doc.title).join('|')==='Title Lab — Welcome|Title Lab — Planning|Title Lab — Кириллица 🪟',containers.map(c=>c.doc.title));
  for(const c of containers)check('native title propagation',native(c)===c.doc.title,{native:native(c),document:c.doc.title});
  plugin.setTemplate('{{vault}} | {{frontmatter["project"]}} | {{filepath}}');await wait(200);
  check('per-window frontmatter',containers.map(c=>c.doc.title).join('|')==='Title Lab | Research | Welcome.md|Title Lab | Planning | Projects/Planning.md|Title Lab | | Projects/Кириллица 🪟.md',containers.map(c=>c.doc.title));
  const file=app.vault.getAbstractFileByPath('Projects/Planning.md');
  await app.fileManager.processFrontMatter(file,fm=>fm.project='Changed');await wait(300);
  check('metadata changes update only appropriate value',containers[1].doc.title.includes('| Changed |')&&containers[0].doc.title.includes('| Research |'),containers.map(c=>c.doc.title));
  await app.fileManager.processFrontMatter(file,fm=>fm.project='Planning');
  ws.setActiveLeaf(main,{focus:true});ws.rootSplit.win.focus();
  graph=ws.getLeaf('tab');await graph.setViewState({type:'graph'});ws.setActiveLeaf(graph,{focus:true});await wait(250);
  check('graph context selected',ws.getMostRecentLeaf(ws.rootSplit)===graph&&graph.view.getViewType()==='graph',graph.view.getViewType());
  plugin.setTemplate('{{vault}} / {{title}} / {{filepath}}');await wait(250);
  check('non-file view has no stale path',document.title==='Title Lab / '+graph.getDisplayText()+' /',document.title);
  graph.detach();graph=null;ws.setActiveLeaf(main,{focus:true});
  app.setting.open();app.setting.openTabById('window-title');await wait(300);
  const settingsTitle=doc().title;
  check('separate settings window exists',doc()!==document,doc().title);
  check('preview uses content active when settings opened',ui().querySelector('.window-title-preview-source').textContent==='Welcome.md',ui().querySelector('.window-title-preview-source').textContent);
  input(textarea(),'{{frontmatter["project"]}} :: {{vault}} :: {{title}}');await wait(250);
  check('template updates visual builder',ui().querySelector('[data-segment-index="0"] .setting-item-name').textContent==='project',ui().innerText);
  check('template updates native output',document.title==='Research :: Title Lab :: Welcome',document.title);
  check('preview equals target window title',ui().querySelector('.window-title-preview-value').textContent===document.title,ui().querySelector('.window-title-preview-value').textContent);
  check('settings title remains untouched',doc().title===settingsTitle,doc().title);
  const literal=ui().querySelector('[data-segment-index="1"] input');
  literal.focus();input(literal,' / ');literal.setSelectionRange(2,2);await wait(100);
  check('builder text updates template',textarea().value==='{{frontmatter["project"]}} / {{vault}} :: {{title}}',textarea().value);
  check('builder preserves focused input',doc().activeElement===literal&&literal.selectionStart===2,{active:doc().activeElement?.tagName,selection:literal.selectionStart});
  const move=ui().querySelector('[data-segment-index="0"] [aria-label="Move later"]');
  check('keyboard reorder control exists',!!move,ui().querySelector('[data-segment-index="0"]').outerHTML);
  move.click();await wait(100);
  check('reorder updates template',textarea().value.startsWith(' / {{frontmatter["project"]}}'),textarea().value);
  const valid=plugin.template;
  input(textarea(),'{{vault');await wait(100);
  check('unfinished template preserves last valid format',plugin.template===valid&&!!ui().querySelector('.window-title-error').textContent,ui().querySelector('.window-title-error').textContent);
  check('unfinished template disables builder',button('Add element').disabled,true);
  button('Use last valid format').click();
  check('discard restores shared format',textarea().value===plugin.template,textarea().value);
  input(textarea(),'{{vault}} — {{title}}');
  button('Add element').click();await wait(250);
  const picker=plugin.settingTab.editor.picker;
  check('native element picker opened',!!picker,doc().body.innerText);
  const suggestions=await picker.getSuggestions('customer');
  check('search finds frontmatter absent from current note',suggestions.some(x=>x.segment.type==='property'&&x.segment.key==='customer name'),suggestions);
  const selected=suggestions.find(x=>x.segment.key==='customer name');picker.onChooseSuggestion(selected);picker.close();await wait(100);
  check('frontmatter insertion updates both editors',textarea().value.endsWith('{{frontmatter["customer name"]}}')&&[...ui().querySelectorAll('.setting-item-name')].some(e=>e.textContent==='customer name'),textarea().value);
  input(textarea(),'{{vault}} — {{title}}');await wait(200);
  const pending=plugin.pendingSaves;await plugin.store.settle();
  check('persisted template matches editor',plugin.store.confirmed.template===textarea().value,{pending,confirmed:plugin.store.confirmed});
  app.setting.close();
  const renamed=app.vault.getAbstractFileByPath('Projects/Кириллица 🪟.md');await app.vault.rename(renamed,'Projects/Renamed 🪟.md');await wait(250);
  check('rename updates title',containers[2].doc.title==='Title Lab — Renamed 🪟',containers[2].doc.title);
  await app.vault.rename(renamed,'Projects/Кириллица 🪟.md');await wait(200);
  await app.plugins.disablePlugin('window-title');await wait(150);
  for(const c of containers)check('disable restores current native title',c.doc.title===expected(c),{actual:c.doc.title,expected:expected(c)});
  await app.plugins.enablePlugin('window-title');plugin=app.plugins.plugins['window-title'];await wait(200);
  check('enable discovers already open popouts',containers.every(c=>c.doc.title==='Title Lab — '+ws.getMostRecentLeaf(c).getDisplayText()),containers.map(c=>c.doc.title));
  const moving=pops[0];ws.moveLeafToPopout(moving);await wait(250);
  check('moved tab retains shared format',moving.getContainer().doc.title==='Title Lab — Planning',moving.getContainer().doc.title);
  plugin.setTemplate(previousTemplate);await plugin.store.settle();
  return {checks,platform:process.platform,electron:process.versions.electron};
} finally {
  app.setting.close();
  graph?.detach();
  for(const leaf of pops)leaf.detach();
  main.detach();
  if(previousLeaf)ws.setActiveLeaf(previousLeaf,{focus:true});
  const current=app.plugins.plugins['window-title'];if(current&&current.template!==previousTemplate){current.setTemplate(previousTemplate);await current.store.settle();}
}
`, 120000);
await writeFile('test-results/runtime.json', JSON.stringify(result, null, 2) + '\n');
const saved = JSON.parse(await readFile(path.join(vaultPath, '.obsidian/plugins/window-title/data.json'), 'utf8'));
assert.equal(saved.version, 1);
console.log(JSON.stringify(result, null, 2));
console.log(await command('Title Lab', 'dev:errors'));
